// Code generated by MockGen. DO NOT EDIT.
// Source: ../vcenter/vcenterops.go

// Package vcenter is a generated GoMock package.
package vcenter

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	object "github.com/vmware/govmomi/object"
)

// MockVCenterOperations is a mock of VCenterOperations interface.
type MockVCenterOperations struct {
	ctrl     *gomock.Controller
	recorder *MockVCenterOperationsMockRecorder
}

// MockVCenterOperationsMockRecorder is the mock recorder for MockVCenterOperations.
type MockVCenterOperationsMockRecorder struct {
	mock *MockVCenterOperations
}

// NewMockVCenterOperations creates a new mock instance.
func NewMockVCenterOperations(ctrl *gomock.Controller) *MockVCenterOperations {
	mock := &MockVCenterOperations{ctrl: ctrl}
	mock.recorder = &MockVCenterOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVCenterOperations) EXPECT() *MockVCenterOperationsMockRecorder {
	return m.recorder
}

// GetVMByName mocks base method.
func (m *MockVCenterOperations) GetVMByName(name string) (*object.VirtualMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMByName", name)
	ret0, _ := ret[0].(*object.VirtualMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMByName indicates an expected call of GetVMByName.
func (mr *MockVCenterOperationsMockRecorder) GetVMByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMByName", reflect.TypeOf((*MockVCenterOperations)(nil).GetVMByName), name)
}

// getDatacenters mocks base method.
func (m *MockVCenterOperations) getDatacenters() ([]*object.Datacenter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getDatacenters")
	ret0, _ := ret[0].([]*object.Datacenter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getDatacenters indicates an expected call of getDatacenters.
func (mr *MockVCenterOperationsMockRecorder) getDatacenters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getDatacenters", reflect.TypeOf((*MockVCenterOperations)(nil).getDatacenters))
}
