apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: vjailbreak-monitoring
  name: loki-storage
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
