apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: vjailbreak-monitoring
  name: loki
  namespace: monitoring
automountServiceAccountToken: false
