apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: promtail
    app.kubernetes.io/name: promtail
    app.kubernetes.io/part-of: vjailbreak-monitoring
  name: promtail
  namespace: monitoring
automountServiceAccountToken: true
