const typography = {
  h1: {
    fontFamily: "Fira Sans",
    fontSize: "50px",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "62px",
    letterSpacing: "normal",
  },
  h2: {
    fontFamily: "Fira Sans",
    fontSize: "37px",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "54px",
    letterSpacing: "normal",
  },
  h3: {
    fontFamily: "Fira Sans",
    fontSize: "28px",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "42px",
    letterSpacing: "normal",
  },
  h4: {
    fontFamily: "Fira Sans",
    fontSize: "21px",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "30px",
    letterSpacing: "normal",
  },
  subtitle1: {
    fontFamily: "Fira Sans",
    fontSize: "21px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "30px",
    letterSpacing: "normal",
  },
  subtitle2: {
    fontFamily: "Fira Sans",
    fontSize: "16px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "24px",
    letterSpacing: "normal",
  },
  body1: {
    fontFamily: "Fira Sans",
    fontSize: "16px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "30px",
    letterSpacing: "normal",
  },
  body2: {
    fontFamily: "Fira Sans",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
  },
  body3: {
    fontFamily: "Fira Sans",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "20px",
    letterSpacing: "normal",
  },
  body3SemiBold: {
    fontFamily: "Fira Sans",
    fontSize: "14px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "20px",
    letterSpacing: "normal",
  },
  body3Bold: {
    fontFamily: "Fira Sans",
    fontSize: "14px",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "20px",
    letterSpacing: "normal",
  },
  caption1: {
    fontFamily: "Fira Sans",
    fontSize: "14px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "20px",
    letterSpacing: "0.8px",
  },
  caption2: {
    fontFamily: "Fira Sans",
    fontSize: "12px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "20px",
    letterSpacing: "0.8px",
  },
  caption3: {
    fontFamily: "Fira Sans",
    fontSize: "11px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "20px",
    letterSpacing: "normal",
  },
  caption4: {
    fontFamily: "Fira Sans",
    fontSize: "12px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "20px",
    letterSpacing: "normal",
  },
}

export default typography
