setup:
	[[ -f flatcar_production_vagrant.box ]] || curl -LO https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_production_vagrant.box
	vagrant box add --force flatcar-alpha flatcar_production_vagrant.box
