@echo off
REM Disk Management Script
echo # Disk Management Status Check Script >> "%~dp0check-disks.ps1"
echo # Reports on disk status and drive letter assignments (READ-ONLY) >> "%~dp0check-disks.ps1"
echo # Run as Administrator >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo param( >> "%~dp0check-disks.ps1"
echo     [string]$LogPath = "C:\DiskStatus_Report.txt" >> "%~dp0check-disks.ps1"
echo ) >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo # Function to log messages >> "%~dp0check-disks.ps1"
echo function Write-Log { >> "%~dp0check-disks.ps1"
echo     param([string]$Message, [string]$Level = "INFO") >> "%~dp0check-disks.ps1"
echo     $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss" >> "%~dp0check-disks.ps1"
echo     $logEntry = "[$timestamp] [$Level] $Message" >> "%~dp0check-disks.ps1"
echo     Write-Host $logEntry >> "%~dp0check-disks.ps1"
echo     Add-Content -Path $LogPath -Value $logEntry >> "%~dp0check-disks.ps1"
echo } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo Write-Log "=== Disk Status Check Started ===" >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo # Check if running as Administrator >> "%~dp0check-disks.ps1"
echo if (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { >> "%~dp0check-disks.ps1"
echo     Write-Log "This script must be run as Administrator!" "ERROR" >> "%~dp0check-disks.ps1"
echo     exit 1 >> "%~dp0check-disks.ps1"
echo } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo Write-Log "Running in READ-ONLY mode - no changes will be made" "INFO" >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo try { >> "%~dp0check-disks.ps1"
echo     # Get all physical disks >> "%~dp0check-disks.ps1"
echo     Write-Log "Scanning for all physical disks..." >> "%~dp0check-disks.ps1"
echo     $physicalDisks = Get-Disk >> "%~dp0check-disks.ps1"
echo     Write-Log "Found $($physicalDisks.Count) physical disk(s)" >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo     # Get all partitions >> "%~dp0check-disks.ps1"
echo     Write-Log "Scanning for partition drive letter assignments..." >> "%~dp0check-disks.ps1"
echo     $allPartitions = Get-Partition >> "%~dp0check-disks.ps1"
echo     $unassignedPartitions = @($allPartitions ^| Where-Object { $_.DriveLetter -eq 0 -and $_.Type -notin @("Recovery", "Reserved", "System", "Dynamic") -and $_.Size -gt 100MB }) >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo     if ($unassignedPartitions.Count -gt 0) { >> "%~dp0check-disks.ps1"
echo         Write-Log "ISSUE: Found $($unassignedPartitions.Count) partition(s) without drive letters" "WARNING" >> "%~dp0check-disks.ps1"
echo         foreach ($partition in $unassignedPartitions) { >> "%~dp0check-disks.ps1"
echo             Write-Log "  - Disk $($partition.DiskNumber), Partition $($partition.PartitionNumber) (Size: $($partition.Size/1GB -as [int]) GB) - NO DRIVE LETTER" "WARNING" >> "%~dp0check-disks.ps1"
echo         } >> "%~dp0check-disks.ps1"
echo     } >> "%~dp0check-disks.ps1"
echo     else { >> "%~dp0check-disks.ps1"
echo         Write-Log "OK: All eligible partitions have drive letters assigned" >> "%~dp0check-disks.ps1"
echo     } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo     # Detailed status report >> "%~dp0check-disks.ps1"
echo     Write-Log "=== Detailed Disk Configuration Status ===" >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo     foreach ($disk in $physicalDisks) { >> "%~dp0check-disks.ps1"
echo         $status = $disk.OperationalStatus >> "%~dp0check-disks.ps1"
echo         $readonly = if ($disk.IsReadOnly) { "Read-Only" } else { "Read-Write" } >> "%~dp0check-disks.ps1"
echo         $health = $disk.HealthStatus >> "%~dp0check-disks.ps1"
echo         Write-Log "Disk $($disk.Number): $status, $readonly, Health: $health, Size: $($disk.Size/1GB -as [int]) GB" >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo         # List partitions for this disk >> "%~dp0check-disks.ps1"
echo         $diskPartitions = @(Get-Partition -DiskNumber $disk.Number -ErrorAction SilentlyContinue) >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo         if ($diskPartitions.Count -gt 0) { >> "%~dp0check-disks.ps1"
echo               Write-Log "  Partition Partition Number: Drive letter, type, size in GB" >> "%~dp0check-disks.ps1"
echo         }         >> "%~dp0check-disks.ps1"
echo         else { >> "%~dp0check-disks.ps1"
echo         Write-Log "  No Partitions Found for this disk" "INFO" >> "%~dp0check-disks.ps1"
echo         } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo         foreach ($partition in $diskPartitions) { >> "%~dp0check-disks.ps1"
echo             $letter = if ($partition.DriveLetter) { $partition.DriveLetter + ":" } else { "No Letter" } >> "%~dp0check-disks.ps1"
echo             $type = $partition.Type >> "%~dp0check-disks.ps1"
echo             $size = $partition.Size/1GB -as [int] >> "%~dp0check-disks.ps1"
echo             Write-Log "  Partition $($partition.PartitionNumber): $letter, $type, $size GB" >> "%~dp0check-disks.ps1"
echo         } >> "%~dp0check-disks.ps1"
echo     } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo     # Summary of issues >> "%~dp0check-disks.ps1"
echo     Write-Log "=== Status Summary ===" >> "%~dp0check-disks.ps1"
echo     $offlineDisks = @($physicalDisks ^| Where-Object { $_.OperationalStatus -eq "Offline" }) >> "%~dp0check-disks.ps1"
echo     $readOnlyDisks = @($physicalDisks ^| Where-Object { $_.IsReadOnly -eq $true }) >> "%~dp0check-disks.ps1"
echo     $unhealthyDisks = @($physicalDisks ^| Where-Object { $_.HealthStatus -ne "Healthy" }) >> "%~dp0check-disks.ps1"
echo      >> "%~dp0check-disks.ps1"
echo     $totalIssues = $offlineDisks.Count + $readOnlyDisks.Count + $unhealthyDisks.Count + $unassignedPartitions.Count >> "%~dp0check-disks.ps1"
echo      >> "%~dp0check-disks.ps1"
echo     if ($totalIssues -eq 0) { >> "%~dp0check-disks.ps1"
echo         Write-Log "ALL CHECKS PASSED: All disks are online, healthy, and all eligible partitions have drive letters assigned" "SUCCESS" >> "%~dp0check-disks.ps1"
echo     } >> "%~dp0check-disks.ps1"
echo     else { >> "%~dp0check-disks.ps1"
echo         Write-Log "ISSUES DETECTED: $totalIssues issue(s) found that may require attention" "WARNING" >> "%~dp0check-disks.ps1"
echo     } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo     if ($offlineDisks.Count -gt 0) { >> "%~dp0check-disks.ps1"
echo         Write-Log "ISSUES FOUND: $($offlineDisks.Count) disk(s) are offline" "WARNING" >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo         foreach ($disk in $offlineDisks) { >> "%~dp0check-disks.ps1"
echo             Write-Log "  - Disk $($disk.Number): $($disk.FriendlyName)" "WARNING" >> "%~dp0check-disks.ps1"
echo         } >> "%~dp0check-disks.ps1"
echo     } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo     if ($readOnlyDisks.Count -gt 0) { >> "%~dp0check-disks.ps1"
echo         Write-Log "ISSUES FOUND: $($readOnlyDisks.Count) disk(s) are read-only" "WARNING" >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo         foreach ($disk in $readOnlyDisks) { >> "%~dp0check-disks.ps1"
echo             Write-Log "  - Disk $($disk.Number): $($disk.FriendlyName)" "WARNING" >> "%~dp0check-disks.ps1"
echo         } >> "%~dp0check-disks.ps1"
echo     } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo     if ($unhealthyDisks.Count -gt 0) { >> "%~dp0check-disks.ps1"
echo         Write-Log "ISSUES FOUND: $($unhealthyDisks.Count) disk(s) have health issues" "WARNING" >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo         foreach ($disk in $unhealthyDisks) { >> "%~dp0check-disks.ps1"
echo             Write-Log "  - Disk $($disk.Number): $($disk.FriendlyName) - Status: $($disk.HealthStatus)" "WARNING" >> "%~dp0check-disks.ps1"
echo         } >> "%~dp0check-disks.ps1"
echo     } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo     if ($unassignedPartitions.Count -gt 0) { >> "%~dp0check-disks.ps1"
echo         Write-Log "ISSUES FOUND: $($unassignedPartitions.Count) partition(s) without drive letters" "WARNING" >> "%~dp0check-disks.ps1"
echo     } >> "%~dp0check-disks.ps1"
echo     >> "%~dp0check-disks.ps1"
echo } >> "%~dp0check-disks.ps1"
echo catch { >> "%~dp0check-disks.ps1"
echo     Write-Log "Critical error during disk status check: $($_.Exception.Message)" "ERROR" >> "%~dp0check-disks.ps1"
echo     exit 1 >> "%~dp0check-disks.ps1"
echo } >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo Write-Log "=== Disk Status Check Completed ===" >> "%~dp0check-disks.ps1"
echo Write-Log "Status report saved to: $LogPath" >> "%~dp0check-disks.ps1"
echo # Summary output >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"
echo Write-Host "- Detailed report saved to: $LogPath" -ForegroundColor Cyan >> "%~dp0check-disks.ps1"
echo. >> "%~dp0check-disks.ps1"

echo Generated check-disks.ps1 successfully!
echo Running Disk checker script...
echo Please note: This script requires Administrator privileges.
echo.

REM Execute the PowerShell script with execution policy bypass
powershell.exe -ExecutionPolicy Bypass -File "%~dp0check-disks.ps1"

echo.
echo Powershell execution completed. Check the log file at C:\DiskStatus_Report.txt for details.
