@echo off
REM Disk Management Status Check and Fix Script Generator
REM Generates check-disks-fix.ps1 and runs it with automatic fixes for offline disks
REM Designed for post-VMware to OpenStack/KVM VM conversion: Blanket-brings all offline disks online
REM WARNING: Assumes unknown pre-migration disk states; use with caution as this may expose intentionally offline disks.
echo # Disk Management Status Check and Fix Script >> "%~dp0check-disks-fix.ps1"
echo # Reports on disk status and drive letter assignments, with automatic fixes for offline disks >> "%~dp0check-disks-fix.ps1"
echo # Run as Administrator >> "%~dp0check-disks-fix.ps1"
echo # >> "%~dp0check-disks-fix.ps1"
echo # DISCLAIMER: This script is intended for automated firstboot after VMware to OpenStack/KVM VM conversion. >> "%~dp0check-disks-fix.ps1"
echo # Pre-migration disk states (online/offline) are unknown and may have been set intentionally. >> "%~dp0check-disks-fix.ps1"
echo # This script will BLANKET ATTEMPT to bring ALL offline disks online without discrimination. >> "%~dp0check-disks-fix.ps1"
echo # Proceed only if this aligns with your migration policy. Always test in a non-production environment. >> "%~dp0check-disks-fix.ps1"
echo # No other changes (e.g., drive letter assignments) are made automatically. >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo [string]$LogPath = "C:\DiskStatus_Report.txt" >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo # Function to log messages >> "%~dp0check-disks-fix.ps1"
echo function Write-Log { >> "%~dp0check-disks-fix.ps1"
echo     param([string]$Message, [string]$Level = "INFO") >> "%~dp0check-disks-fix.ps1"
echo     $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss" >> "%~dp0check-disks-fix.ps1"
echo     $logEntry = "[$timestamp] [$Level] $Message" >> "%~dp0check-disks-fix.ps1"
echo     Write-Host $logEntry >> "%~dp0check-disks-fix.ps1"
echo     Add-Content -Path $LogPath -Value $logEntry >> "%~dp0check-disks-fix.ps1"
echo } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo Write-Log "=== Disk Status Check Started (Post-VMware to KVM Migration Fix Mode) ===" >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo # Check if running as Administrator >> "%~dp0check-disks-fix.ps1"
echo if (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { >> "%~dp0check-disks-fix.ps1"
echo     Write-Log "This script must be run as Administrator!" "ERROR" >> "%~dp0check-disks-fix.ps1"
echo     exit 1 >> "%~dp0check-disks-fix.ps1"
echo } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo Write-Log "Running in AUTO-FIX MODE - Blanket attempting to bring all offline disks online" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo Write-Log "Context: Post-VMware to OpenStack/KVM conversion. Pre-migration disk states unknown." "INFO" >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo try { >> "%~dp0check-disks-fix.ps1"
echo     # Get all physical disks >> "%~dp0check-disks-fix.ps1"
echo     Write-Log "Scanning for all physical disks..." >> "%~dp0check-disks-fix.ps1"
echo     $physicalDisks = Get-Disk >> "%~dp0check-disks-fix.ps1"
echo     Write-Log "Found $($physicalDisks.Count) physical disk(s)" >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     # Get all partitions >> "%~dp0check-disks-fix.ps1"
echo     Write-Log "Scanning for partition drive letter assignments..." >> "%~dp0check-disks-fix.ps1"
echo     $allPartitions = Get-Partition >> "%~dp0check-disks-fix.ps1"
echo     $unassignedPartitions = @($allPartitions | Where-Object { $_.DriveLetter -eq 0 -and $_.Type -notin @("Recovery", "Reserved", "System", "Dynamic") -and $_.Size -gt 100MB }) >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     if ($unassignedPartitions.Count -gt 0) { >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "ISSUE: Found $($unassignedPartitions.Count) partition(s) without drive letters" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo         foreach ($partition in $unassignedPartitions) { >> "%~dp0check-disks-fix.ps1"
echo             Write-Log " - Disk $($partition.DiskNumber), Partition $($partition.PartitionNumber) (Size: $($partition.Size/1GB -as [int]) GB) - NO DRIVE LETTER" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo         } >> "%~dp0check-disks-fix.ps1"
echo     } else { >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "OK: All eligible partitions have drive letters assigned" "INFO" >> "%~dp0check-disks-fix.ps1"
echo     } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     # Detailed status report >> "%~dp0check-disks-fix.ps1"
echo     Write-Log "=== Detailed Disk Configuration Status ===" >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     foreach ($disk in $physicalDisks) { >> "%~dp0check-disks-fix.ps1"
echo         $status = $disk.OperationalStatus >> "%~dp0check-disks-fix.ps1"
echo         $readonly = if ($disk.IsReadOnly) { "Read-Only" } else { "Read-Write" } >> "%~dp0check-disks-fix.ps1"
echo         $health = $disk.HealthStatus >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "Disk $($disk.Number): $status, $readonly, Health: $health, Size: $($disk.Size/1GB -as [int]) GB" >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo         # List partitions for this disk >> "%~dp0check-disks-fix.ps1"
echo         $diskPartitions = @(Get-Partition -DiskNumber $disk.Number -ErrorAction SilentlyContinue) >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo         if ($diskPartitions.Count -gt 0) { >> "%~dp0check-disks-fix.ps1"
echo             Write-Log " Partition Partition Number: Drive letter, type, size in GB" >> "%~dp0check-disks-fix.ps1"
echo         } else { >> "%~dp0check-disks-fix.ps1"
echo             Write-Log " No Partitions Found for this disk" "INFO" >> "%~dp0check-disks-fix.ps1"
echo         } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo         foreach ($partition in $diskPartitions) { >> "%~dp0check-disks-fix.ps1"
echo             $letter = if ($partition.DriveLetter) { $partition.DriveLetter + ":" } else { "No Letter" } >> "%~dp0check-disks-fix.ps1"
echo             $type = $partition.Type >> "%~dp0check-disks-fix.ps1"
echo             $size = $partition.Size/1GB -as [int] >> "%~dp0check-disks-fix.ps1"
echo             Write-Log " Partition $($partition.PartitionNumber): $letter, $type, $size GB" >> "%~dp0check-disks-fix.ps1"
echo         } >> "%~dp0check-disks-fix.ps1"
echo     } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     # Summary of issues >> "%~dp0check-disks-fix.ps1"
echo     Write-Log "=== Status Summary ===" >> "%~dp0check-disks-fix.ps1"
echo     $offlineDisks = @($physicalDisks | Where-Object { $_.OperationalStatus -eq "Offline" }) >> "%~dp0check-disks-fix.ps1"
echo     $readOnlyDisks = @($physicalDisks | Where-Object { $_.IsReadOnly -eq $true }) >> "%~dp0check-disks-fix.ps1"
echo     $unhealthyDisks = @($physicalDisks | Where-Object { $_.HealthStatus -ne "Healthy" }) >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     $totalIssues = $offlineDisks.Count + $readOnlyDisks.Count + $unhealthyDisks.Count + $unassignedPartitions.Count >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     if ($totalIssues -eq 0) { >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "ALL CHECKS PASSED: All disks are online, healthy, and all eligible partitions have drive letters assigned" "SUCCESS" >> "%~dp0check-disks-fix.ps1"
echo     } else { >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "ISSUES DETECTED: $totalIssues issue(s) found that may require attention" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo     } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     if ($offlineDisks.Count -gt 0) { >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "ISSUES FOUND: $($offlineDisks.Count) disk(s) are offline" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo         foreach ($disk in $offlineDisks) { >> "%~dp0check-disks-fix.ps1"
echo             Write-Log " - Disk $($disk.Number): $($disk.FriendlyName)" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo         } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo         # AUTO-FIX: Blanket attempt to bring all offline disks online >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "Attempting to bring all offline disks online..." "INFO" >> "%~dp0check-disks-fix.ps1"
echo         $fixedCount = 0 >> "%~dp0check-disks-fix.ps1"
echo         $failedCount = 0 >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo         foreach ($disk in $offlineDisks) { >> "%~dp0check-disks-fix.ps1"
echo             try { >> "%~dp0check-disks-fix.ps1"
echo                 Write-Log "Attempting to bring Disk $($disk.Number) online..." "INFO" >> "%~dp0check-disks-fix.ps1"
echo                 Set-Disk -Number $disk.Number -IsOffline $false -ErrorAction Stop >> "%~dp0check-disks-fix.ps1"
echo                 Write-Log "SUCCESS: Disk $($disk.Number) is now online" "SUCCESS" >> "%~dp0check-disks-fix.ps1"
echo                 $fixedCount++ >> "%~dp0check-disks-fix.ps1"
echo             } >> "%~dp0check-disks-fix.ps1"
echo             catch { >> "%~dp0check-disks-fix.ps1"
echo                 Write-Log "FAILED to bring Disk $($disk.Number) online: $($_.Exception.Message)" "ERROR" >> "%~dp0check-disks-fix.ps1"
echo                 $failedCount++ >> "%~dp0check-disks-fix.ps1"
echo             } >> "%~dp0check-disks-fix.ps1"
echo         } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "Fix Summary: $fixedCount disk(s) brought online, $failedCount failed" "INFO" >> "%~dp0check-disks-fix.ps1"
echo     } else { >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "OK: No offline disks detected" "INFO" >> "%~dp0check-disks-fix.ps1"
echo     } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     if ($readOnlyDisks.Count -gt 0) { >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "ISSUES FOUND: $($readOnlyDisks.Count) disk(s) are read-only" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo         foreach ($disk in $readOnlyDisks) { >> "%~dp0check-disks-fix.ps1"
echo             Write-Log " - Disk $($disk.Number): $($disk.FriendlyName)" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo         } >> "%~dp0check-disks-fix.ps1"
echo     } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     if ($unhealthyDisks.Count -gt 0) { >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "ISSUES FOUND: $($unhealthyDisks.Count) disk(s) have health issues" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo         foreach ($disk in $unhealthyDisks) { >> "%~dp0check-disks-fix.ps1"
echo             Write-Log " - Disk $($disk.Number): $($disk.FriendlyName) - Status: $($disk.HealthStatus)" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo         } >> "%~dp0check-disks-fix.ps1"
echo     } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo     if ($unassignedPartitions.Count -gt 0) { >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "ISSUES FOUND: $($unassignedPartitions.Count) partition(s) without drive letters" "WARNING" >> "%~dp0check-disks-fix.ps1"
echo         Write-Log "Note: Drive letter assignment is not automated in this script to avoid conflicts. Use Disk Management GUI or additional cmdlets if needed." "INFO" >> "%~dp0check-disks-fix.ps1"
echo     } >> "%~dp0check-disks-fix.ps1"
echo } >> "%~dp0check-disks-fix.ps1"
echo catch { >> "%~dp0check-disks-fix.ps1"
echo     Write-Log "Critical error during disk status check: $($_.Exception.Message)" "ERROR" >> "%~dp0check-disks-fix.ps1"
echo     exit 1 >> "%~dp0check-disks-fix.ps1"
echo } >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo Write-Log "=== Disk Status Check Completed ===" >> "%~dp0check-disks-fix.ps1"
echo Write-Log "Status report saved to: $LogPath" >> "%~dp0check-disks-fix.ps1"
echo # Summary output >> "%~dp0check-disks-fix.ps1"
echo. >> "%~dp0check-disks-fix.ps1"
echo Write-Host "- Detailed report saved to: $LogPath" -ForegroundColor Cyan >> "%~dp0check-disks-fix.ps1"

echo.
echo Generated check-disks-fix.ps1 successfully!
echo Running Disk checker script with automatic offline disk fixes...
echo Please note: This script requires Administrator privileges and will blanket-bring all offline disks online.
echo.
REM Execute the PowerShell script with execution policy bypass (no switch needed; fixes are hardcoded)
powershell.exe -ExecutionPolicy Bypass -File "%~dp0check-disks-fix.ps1"
echo.
echo Powershell execution completed. Check the log file at C:\DiskStatus_Report.txt for details.