apiVersion: vjailbreak.k8s.pf9.io/v1alpha1
kind: MigrationTemplate
metadata:
  name: migrationtemplate-windows
  namespace: migration-system
spec:
  networkMapping: networkmapping 
  storageMapping: storagemapping
  osType: windows 
  source:
    datacenter: Datacenter Name 
    vmwareRef: vmwarecreds
  destination:
    openstackRef: openstackcreds