apiVersion: vjailbreak.k8s.pf9.io/v1alpha1
kind: VolumeImageProfile
metadata:
  name: default-windows
  namespace: migration-system
spec:
  osFamily: windowsGuest
  description: Default profile for Windows VMs
  properties:
    hw_qemu_guest_agent: "yes"
    hw_video_model: virtio
    hw_pointer_model: usbtablet
    hw_disk_bus: virtio
    os_type: windows
---
apiVersion: vjailbreak.k8s.pf9.io/v1alpha1
kind: VolumeImageProfile
metadata:
  name: default-linux
  namespace: migration-system
spec:
  osFamily: linuxGuest
  description: Default profile for Linux VMs
  properties:
    hw_qemu_guest_agent: "yes"
    hw_video_model: virtio
    hw_pointer_model: usbtablet
