version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - staticcheck
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
      - path: pkg/scope
        linters:
          - dupl
    paths:
      - test
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    dupl:
      threshold: 100
