---
# Self-signed ClusterIssuer for IP-based deployments
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# CA Certificate for signing
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vjailbreak-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: vjailbreak-ca
  secretName: vjailbreak-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# CA Issuer using the CA certificate
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vjailbreak-ca-issuer
spec:
  ca:
    secretName: vjailbreak-ca-secret