apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: oauth2-proxy
data:
  oauth2_proxy.cfg: |
    # OAuth provider configuration
    provider = "oidc"
    provider_display_name = "vJailbreak Login"
    
    # Dex OIDC configuration (will be updated by setup script with actual IP)
    # Note: Dex is exposed via Ingress on port 80, not directly on port 5556
    oidc_issuer_url = "http://HOST_IP/dex"
    redirect_url = "http://HOST_IP/oauth2/callback"
    
    # OAuth2 endpoints
    login_url = "http://HOST_IP/dex/auth"
    redeem_url = "http://dex.dex.svc.cluster.local:5556/dex/token"
    oidc_jwks_url = "http://dex.dex.svc.cluster.local:5556/dex/keys"
    
    # Email and user configuration
    email_domains = ["*"]
    whitelist_domains = []
    
    # Cookie configuration
    cookie_name = "_oauth2_proxy"
    cookie_secure = false
    cookie_httponly = true
    cookie_samesite = "lax"
    cookie_domains = []
    cookie_expire = "168h"
    cookie_refresh = "1h"
    
    # Request configuration
    upstreams = ["http://vjailbreak-ui-service.migration-system.svc.cluster.local:80"]
    http_address = "0.0.0.0:4180"
    reverse_proxy = true
    
    # Authentication configuration
    skip_provider_button = false
    skip_auth_routes = [
      "^/health$",
      "^/ping$"
    ]
    
    # Pass authentication info to upstream
    pass_access_token = true
    pass_authorization_header = true
    pass_user_headers = true
    set_xauthrequest = true
    set_authorization_header = true
    
    # Scope configuration - request groups for RBAC
    scope = "openid profile email groups offline_access"
    
    # Session configuration
    session_cookie_minimal = false
    
    # Logging
    request_logging = true
    auth_logging = true
    standard_logging = true
