apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4180
    targetPort: http
    protocol: TCP
  selector:
    app: oauth2-proxy
