// Code generated by MockGen. DO NOT EDIT.
// Source: vmops.go

// Package vm is a generated GoMock package.
package vm

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	object "github.com/vmware/govmomi/object"
	types "github.com/vmware/govmomi/vim25/types"
)

// MockVMOperations is a mock of VMOperations interface.
type MockVMOperations struct {
	ctrl     *gomock.Controller
	recorder *MockVMOperationsMockRecorder
}

// MockVMOperationsMockRecorder is the mock recorder for MockVMOperations.
type MockVMOperationsMockRecorder struct {
	mock *MockVMOperations
}

// NewMockVMOperations creates a new mock instance.
func NewMockVMOperations(ctrl *gomock.Controller) *MockVMOperations {
	mock := &MockVMOperations{ctrl: ctrl}
	mock.recorder = &MockVMOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVMOperations) EXPECT() *MockVMOperationsMockRecorder {
	return m.recorder
}

// CleanUpSnapshots mocks base method.
func (m *MockVMOperations) CleanUpSnapshots(ignoreerror bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanUpSnapshots", ignoreerror)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanUpSnapshots indicates an expected call of CleanUpSnapshots.
func (mr *MockVMOperationsMockRecorder) CleanUpSnapshots(ignoreerror interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanUpSnapshots", reflect.TypeOf((*MockVMOperations)(nil).CleanUpSnapshots), ignoreerror)
}

// CustomQueryChangedDiskAreas mocks base method.
func (m *MockVMOperations) CustomQueryChangedDiskAreas(baseChangeID string, curSnapshot *types.ManagedObjectReference, disk *types.VirtualDisk, offset int64) (types.DiskChangeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomQueryChangedDiskAreas", baseChangeID, curSnapshot, disk, offset)
	ret0, _ := ret[0].(types.DiskChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CustomQueryChangedDiskAreas indicates an expected call of CustomQueryChangedDiskAreas.
func (mr *MockVMOperationsMockRecorder) CustomQueryChangedDiskAreas(baseChangeID, curSnapshot, disk, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomQueryChangedDiskAreas", reflect.TypeOf((*MockVMOperations)(nil).CustomQueryChangedDiskAreas), baseChangeID, curSnapshot, disk, offset)
}

// DeleteMigrationSnapshots mocks base method.
func (m *MockVMOperations) DeleteMigrationSnapshots(snapshots []types.VirtualMachineSnapshotTree, ignoreerror bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMigrationSnapshots", snapshots, ignoreerror)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMigrationSnapshots indicates an expected call of DeleteMigrationSnapshots.
func (mr *MockVMOperationsMockRecorder) DeleteMigrationSnapshots(snapshots, ignoreerror interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMigrationSnapshots", reflect.TypeOf((*MockVMOperations)(nil).DeleteMigrationSnapshots), snapshots, ignoreerror)
}

// DeleteSnapshot mocks base method.
func (m *MockVMOperations) DeleteSnapshot(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockVMOperationsMockRecorder) DeleteSnapshot(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockVMOperations)(nil).DeleteSnapshot), name)
}

// DeleteSnapshotByRef mocks base method.
func (m *MockVMOperations) DeleteSnapshotByRef(snap *types.ManagedObjectReference) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshotByRef", snap)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSnapshotByRef indicates an expected call of DeleteSnapshotByRef.
func (mr *MockVMOperationsMockRecorder) DeleteSnapshotByRef(snap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshotByRef", reflect.TypeOf((*MockVMOperations)(nil).DeleteSnapshotByRef), snap)
}

// DisconnectNetworkInterfaces mocks base method.
func (m *MockVMOperations) DisconnectNetworkInterfaces() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisconnectNetworkInterfaces")
	ret0, _ := ret[0].(error)
	return ret0
}

// DisconnectNetworkInterfaces indicates an expected call of DisconnectNetworkInterfaces.
func (mr *MockVMOperationsMockRecorder) DisconnectNetworkInterfaces() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectNetworkInterfaces", reflect.TypeOf((*MockVMOperations)(nil).DisconnectNetworkInterfaces))
}

// EnableCBT mocks base method.
func (m *MockVMOperations) EnableCBT() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableCBT")
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableCBT indicates an expected call of EnableCBT.
func (mr *MockVMOperationsMockRecorder) EnableCBT() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableCBT", reflect.TypeOf((*MockVMOperations)(nil).EnableCBT))
}

// GetSnapshot mocks base method.
func (m *MockVMOperations) GetSnapshot(name string) (*types.ManagedObjectReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshot", name)
	ret0, _ := ret[0].(*types.ManagedObjectReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockVMOperationsMockRecorder) GetSnapshot(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*MockVMOperations)(nil).GetSnapshot), name)
}

// GetVMInfo mocks base method.
func (m *MockVMOperations) GetVMInfo(ostype string, rdmDisks []string) (VMInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMInfo", ostype, rdmDisks)
	ret0, _ := ret[0].(VMInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMInfo indicates an expected call of GetVMInfo.
func (mr *MockVMOperationsMockRecorder) GetVMInfo(ostype, rdmDisks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMInfo", reflect.TypeOf((*MockVMOperations)(nil).GetVMInfo), ostype, rdmDisks)
}

// GetVMObj mocks base method.
func (m *MockVMOperations) GetVMObj() *object.VirtualMachine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMObj")
	ret0, _ := ret[0].(*object.VirtualMachine)
	return ret0
}

// GetVMObj indicates an expected call of GetVMObj.
func (mr *MockVMOperationsMockRecorder) GetVMObj() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMObj", reflect.TypeOf((*MockVMOperations)(nil).GetVMObj))
}

// IsCBTEnabled mocks base method.
func (m *MockVMOperations) IsCBTEnabled() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCBTEnabled")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCBTEnabled indicates an expected call of IsCBTEnabled.
func (mr *MockVMOperationsMockRecorder) IsCBTEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCBTEnabled", reflect.TypeOf((*MockVMOperations)(nil).IsCBTEnabled))
}

// ListSnapshots mocks base method.
func (m *MockVMOperations) ListSnapshots() ([]types.VirtualMachineSnapshotTree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSnapshots")
	ret0, _ := ret[0].([]types.VirtualMachineSnapshotTree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSnapshots indicates an expected call of ListSnapshots.
func (mr *MockVMOperationsMockRecorder) ListSnapshots() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSnapshots", reflect.TypeOf((*MockVMOperations)(nil).ListSnapshots))
}

// TakeSnapshot mocks base method.
func (m *MockVMOperations) TakeSnapshot(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeSnapshot", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// TakeSnapshot indicates an expected call of TakeSnapshot.
func (mr *MockVMOperationsMockRecorder) TakeSnapshot(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeSnapshot", reflect.TypeOf((*MockVMOperations)(nil).TakeSnapshot), name)
}

// UpdateDiskInfo mocks base method.
func (m *MockVMOperations) UpdateDiskInfo(arg0 *VMInfo, arg1 VMDisk, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiskInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDiskInfo indicates an expected call of UpdateDiskInfo.
func (mr *MockVMOperationsMockRecorder) UpdateDiskInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiskInfo", reflect.TypeOf((*MockVMOperations)(nil).UpdateDiskInfo), arg0, arg1, arg2)
}

// UpdateDisksInfo mocks base method.
func (m *MockVMOperations) UpdateDisksInfo(arg0 *VMInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDisksInfo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDisksInfo indicates an expected call of UpdateDisksInfo.
func (mr *MockVMOperationsMockRecorder) UpdateDisksInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDisksInfo", reflect.TypeOf((*MockVMOperations)(nil).UpdateDisksInfo), arg0)
}

// VMGuestShutdown mocks base method.
func (m *MockVMOperations) VMGuestShutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VMGuestShutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// VMGuestShutdown indicates an expected call of VMGuestShutdown.
func (mr *MockVMOperationsMockRecorder) VMGuestShutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VMGuestShutdown", reflect.TypeOf((*MockVMOperations)(nil).VMGuestShutdown))
}

// VMPowerOff mocks base method.
func (m *MockVMOperations) VMPowerOff() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VMPowerOff")
	ret0, _ := ret[0].(error)
	return ret0
}

// VMPowerOff indicates an expected call of VMPowerOff.
func (mr *MockVMOperationsMockRecorder) VMPowerOff() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VMPowerOff", reflect.TypeOf((*MockVMOperations)(nil).VMPowerOff))
}

// VMPowerOn mocks base method.
func (m *MockVMOperations) VMPowerOn() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VMPowerOn")
	ret0, _ := ret[0].(error)
	return ret0
}

// VMPowerOn indicates an expected call of VMPowerOn.
func (mr *MockVMOperationsMockRecorder) VMPowerOn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VMPowerOn", reflect.TypeOf((*MockVMOperations)(nil).VMPowerOn))
}
