# permissions for end users to edit esximigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: esximigration-editor-role
rules:
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - esximigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - esximigrations/status
  verbs:
  - get
