# permissions for end users to view migrationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: migrationtemplate-viewer-role
rules:
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - migrationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - migrationtemplates/status
  verbs:
  - get
