# This rule is not used by the project migration itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vjailbreak.k8s.pf9.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: rdmdisk-viewer-role
rules:
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - rdmdisks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - rdmdisks/status
  verbs:
  - get
