# This rule is not used by the project migration itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the vjailbreak.k8s.pf9.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: rdmdisk-editor-role
rules:
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - rdmdisks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - rdmdisks/status
  verbs:
  - get
