# permissions for end users to edit rollingmigrationplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: rollingmigrationplan-editor-role
rules:
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - rollingmigrationplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - rollingmigrationplans/status
  verbs:
  - get
