---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: v2v-helper-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - arraycreds
  - migrations
  - migrationtemplates
  - rdmdisks
  - storagemappings
  - vjailbreaknodes
  - vmwarecreds
  - vmwaremachines
  verbs:
  - get
  - list
  - watch
