# permissions for end users to view vjailbreaknodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: vjailbreaknode-viewer-role
rules:
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - vjailbreaknodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - vjailbreaknodes/status
  verbs:
  - get
