# permissions for end users to view vmwarecreds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: vmwarecreds-viewer-role
rules:
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - vmwarecreds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - vmwarecreds/status
  verbs:
  - get
