apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-pvc
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-postgres
  template:
    metadata:
      labels:
        app: authentik-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: authentik
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: authentik-postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgres-secret
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: authentik-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  selector:
    app: authentik-postgres
  ports:
  - port: 5432
    targetPort: 5432